import { Suspense, lazy, useState } from 'react';
import type { Location, Store } from '../shared/types';
import { StoreActions } from '../components/StoreRow';
import { WEEK_DAYS, hoursToday } from '../shared/hours';
const StoreMap = lazy(() => import('../components/StoreMap'));
export default function Stores({ stores, favourites, toggleFavourite, onOpen, location }: { stores: Store[]; favourites: string[]; toggleFavourite: (code: string) => void; onOpen: (store: Store) => void; location: Location }) {
  const [query, setQuery] = useState(''), [state, setState] = useState(''), [saved, setSaved] = useState(false);
  const filtered = stores.filter(s => `${s.name} ${s.suburb} ${s.postcode}`.toLowerCase().includes(query.toLowerCase()) && (!state || s.state === state) && (!saved || favourites.includes(s.code))).sort((a, b) => (a.distanceMetres ?? Infinity) - (b.distanceMetres ?? Infinity));
  return <section><div className="page-heading"><div><span className="eyebrow">YOUR LOCAL STORES</span><h1>A little closer.</h1><p className="muted">Stores discovered during your stock checks, nearest first.</p></div></div><div className="directory-filters"><label>Search stores<input value={query} onChange={e => setQuery(e.target.value)} placeholder="Name, suburb or postcode"/></label><label>State<select value={state} onChange={e => setState(e.target.value)}><option value="">Any state</option>{['VIC', 'NSW', 'QLD', 'SA', 'WA', 'TAS', 'ACT', 'NT'].map(s => <option key={s}>{s}</option>)}</select></label><label className="check"><input type="checkbox" checked={saved} onChange={e => setSaved(e.target.checked)}/> Favourites only</label></div>{!filtered.length ? <div className="empty"><h2>{stores.length ? 'No matching stores' : 'Your store list starts with a search.'}</h2><p>Run a stock check to discover nearby Telstra stores. They’ll be saved here.</p></div> : <div className="stores-layout"><ul className="stores-list">{filtered.map(store => <li className="store-card" key={store.code}><div className="store-card-head"><div><h2><button className="title-button" onClick={() => onOpen(store)}>{store.name}</button></h2><p className="muted">{store.suburb} {store.state} {store.postcode} <span className="dot">·</span> {hoursToday(store)}</p></div><div className="store-card-side"><span className="distance-chip">{store.distanceMetres === null ? '–' : `${(store.distanceMetres / 1000).toFixed(1)} km`}</span><button className="star" aria-label={`${favourites.includes(store.code) ? 'Unsave' : 'Save'} ${store.name}`} aria-pressed={favourites.includes(store.code)} onClick={() => toggleFavourite(store.code)}>{favourites.includes(store.code) ? '★' : '☆'}</button></div></div><details className="store-details"><summary>Store details</summary><ul className="hours-list">{WEEK_DAYS.map(([key, label]) => <li key={key}><span>{label}</span><span>{store.hours[key] || 'Closed'}</span></li>)}</ul></details><StoreActions store={store}/></li>)}</ul><div className="stores-map-pane"><Suspense fallback={<div className="store-map"/>}><StoreMap stores={filtered} stock={[]} center={location} onSelect={onOpen}/></Suspense></div></div>}</section>;
}
