import type { ProductVariant, Stock, Store } from '../shared/types';
import { available, stockKey } from '../shared/scan';
import { hoursToday } from '../shared/hours';
export function StoreActions({ store }: { store: Store }) {
  const destination = store.latitude !== null && store.longitude !== null ? `${store.latitude},${store.longitude}` : `${store.address} ${store.suburb} ${store.state} ${store.postcode}`;
  return <div className="store-actions">{store.phone && <a className="button secondary" href={`tel:${store.phone.replace(/[^+\d]/g, '')}`}>Call store <span aria-hidden="true">↗</span></a>}<a className="button ghost" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(destination)}`}>Directions <span aria-hidden="true">↗</span></a></div>;
}
export default function StoreRow({ store, stock, products, diff = {}, favourite, onFavourite, onOpen }: { store: Store; stock: Stock[]; products: ProductVariant[]; diff?: Record<string, 'new' | 'gone'>; favourite: boolean; onFavourite: () => void; onOpen: () => void }) {
  const records = stock.filter(s => s.storeCode === store.code), inStock = records.filter(available);
  const knownUnavailable = records.length === products.length && records.every(s => s.status === 'unavailable');
  const visible = inStock.length ? inStock : records.filter(s => diff[stockKey(s)] === 'gone');
  return <article className="store-row"><div className="store-main"><div className="store-heading"><div><div className="eyebrow">TELSTRA STORE <span>· {store.distanceMetres === null ? 'Distance unknown' : `${(store.distanceMetres / 1000).toFixed(1)} km`}</span></div><h3><button className="title-button" onClick={onOpen}>{store.name}</button></h3></div><button className="star" aria-label={`${favourite ? 'Unsave' : 'Save'} ${store.name}`} aria-pressed={favourite} onClick={onFavourite}>{favourite ? '★' : '☆'}</button></div><p className="muted">{store.suburb} {store.state} {store.postcode} <span className="dot">·</span> {hoursToday(store)}</p><StoreActions store={store}/></div><div className="store-stock"><span className={inStock.length ? 'badge available' : 'badge'}>{inStock.length ? `✓ ${inStock.length} available` : knownUnavailable ? 'Unavailable' : 'Stock not fully checked'}</span><ul className="variant-list">{visible.map(s => { const product = products.find(p => p.sku === s.sku); return product ? <li key={s.sku}><span>{product.model}<strong>{product.storage} <span className="dot">·</span> {product.colour}</strong><small>{s.usageType === 'inStoreOnly' ? 'In store only' : s.usageType === 'pickupUnavailable' ? 'Pickup unavailable' : s.usageType || 'Ask store for collection options'}</small></span>{diff[stockKey(s)] && <span className={diff[stockKey(s)] === 'new' ? 'new-stock' : 'muted'}>{diff[stockKey(s)] === 'new' ? 'NEW STOCK' : 'No longer available'}</span>}</li> : null; })}</ul><button className="text-button" onClick={onOpen}>View all stock at this store <span aria-hidden="true">→</span></button></div></article>;
}
